### ISSUE TITLE
代码显示错误

### ISSUE THREAD

**Issue by PolarLinda6** [liuyubing233/zhihu-custom-mobile#17]
启用脚本，代码框消失
![Screenshot_2024-09-23-01-45-34-196_mark.via-edit.jpg](https://github.com/user-attachments/assets/9462049a-0e8c-47ec-aa45-649ff69584f1)

原渲染
![Screenshot_2024-09-23-01-45-50-926_mark.via.jpg](https://github.com/user-attachments/assets/b9aa726d-0d92-4b7d-8d39-a6b2cc8bf65e)

**Comment by liuyubing233** [comment]
使用的是什么版本的？有没有关闭其他脚本尝试一下

**Comment by PolarLinda6** [comment]
2.9.1 没有开其他脚本
![Screenshot_2024-09-26-12-08-52-516_mark.via.jpg](https://github.com/user-attachments/assets/c384f486-5615-4fcb-8fd6-71f447896950)

![Screenshot_2024-09-26-12-08-55-909_mark.via.jpg](https://github.com/user-attachments/assets/64f1b6e2-e6e9-4abc-b913-6cb3a1604de5)
