### ISSUE TITLE
建议增加知乎原有搜索框

### ISSUE THREAD

**Issue by PolarLinda6** [liuyubing233/zhihu-custom-mobile#18]
如题

**Comment by liuyubing233** [comment]
已添加

**Comment by PolarLinda6** [comment]
![Screenshot_2024-09-26-12-17-35-673_mark.via.png](https://github.com/user-attachments/assets/8c7be62a-992b-41cd-bf48-a36b27e69052)

希望将搜索栏改为类似的底边栏并常驻所有界面

1. 首页按钮: 可以随时跳转首页
2. 搜索按钮: 原有搜索栏太高
3. 主页按钮: 可以跳转自己的主页

ps: 搜索栏无法使用回车搜索，望修复
